name: Verify Commit Messages
on:
  pull_request:
    branches:
      - 'feature/**'
      - 'hotfix/**'
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'
jobs:
  verify-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '([A-Z]{1,5}-[0-9]+|NA):.[A-Z].*$'
          checkAllCommitMessages: 'true'
          error: 'ERROR: Your commit message does not match our agreed upon pattern'