name: Verify Commit Messages
on:
  pull_request:
    branches:
      - 'feature/**'
      - 'hotfix/**'
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'
jobs:
  verify-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Commit Type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '\[[^]]+\] .+$\'
          checkAllCommitMessages: 'true'
          error: 'ERROR: the pattern does not match'